from .actionAngle import actionAngle

class actionAngleInverse(actionAngle):
    def __call__(self, *args: object, **kwargs: object) -> object: ...
    def xvFreqs(self, *args: object, **kwargs: object) -> object: ...
    def Freqs(self, *args: object, **kwargs: object) -> object: ...
