from ..potential._typing import Numeric, QuantityLike

class galpy_profile:
    """Optional AMUSE adapter for a galpy potential."""

    def __init__(
        self,
        pot: object,
        t: Numeric | QuantityLike = 0.0,
        tgalpy: Numeric | QuantityLike = 0.0,
        ro: Numeric | QuantityLike | None = None,
        vo: Numeric | QuantityLike | None = None,
        reverse: bool = False,
    ) -> None: ...
    def evolve_model(self, time: Numeric | QuantityLike) -> None: ...
    def get_potential_at_point(
        self, eps: object, x: object, y: object, z: object
    ) -> object: ...
    def get_gravity_at_point(
        self, eps: object, x: object, y: object, z: object
    ) -> tuple[object, object, object]: ...
    def mass_density(self, x: object, y: object, z: object) -> object: ...
    def circular_velocity(self, r: object) -> object: ...
    def enclosed_mass(self, r: object) -> object: ...
    def stop(self) -> None: ...
