from ._typing import Numeric

old_error_settings = ...
ro = ...
vo = ...
sigo = ...
rhoo = ...
fb = ...
m200 = ...
conc = ...
r0_bulge = ...
rcut_bulge = ...
rho0_bulge = ...
zd_thin = ...
Rd_thin = ...
Sigma0_thin = ...
zd_thick = ...
Rd_thick = ...
Sigma0_thick = ...
Rd_HI = ...
Rm_HI = ...
zd_HI = ...
Sigma0_HI = ...
Rd_H2 = ...
Rm_H2 = ...
zd_H2 = ...
Sigma0_H2 = ...
A = ...
Beta = ...
critz0 = ...
R200 = ...
cgm_amp = ...

def gas_dens(R: Numeric, z: Numeric) -> Numeric: ...
def stellar_dens(R: Numeric, z: Numeric) -> Numeric: ...
def bulge_dens(R: Numeric, z: Numeric) -> Numeric: ...

sigmadict = ...
hzdict = ...
Cautun_bulge = ...
Cautun_cgm = ...
Cautun_disk = ...
Cautun_halo = ...
Cautun20 = ...
