from collections.abc import Generator
from typing import Self, override

from ._typing import Number, QuantityLike, Numeric

class linearPotential:
    dim: int
    _amp: object
    def __init__(
        self,
        amp: QuantityLike = 1.0,
        ro: QuantityLike | None = None,
        vo: QuantityLike | None = None,
    ) -> None: ...
    @override
    def __repr__(self) -> str: ...
    def __mul__(self, b: Number) -> Self: ...
    __rmul__ = __mul__
    def __truediv__(self, b: Number) -> Self: ...
    __div__ = __truediv__
    def __len__(self) -> int: ...
    def __iter__(self) -> Generator[Self, None, None]: ...
    def __add__(self, b: linearPotential) -> object: ...
    def __radd__(self, b: linearPotential) -> object: ...
    def turn_physical_off(self) -> None: ...
    def turn_physical_on(
        self, ro: QuantityLike | None = None, vo: QuantityLike | None = None
    ) -> None: ...
    def __call__(self, x: Numeric, t: Numeric = 0.0) -> Numeric: ...
    def force(self, x: Numeric, t: Numeric = 0.0) -> Numeric: ...
