from typing import override

from .CompositePotential import CompositePotential
from .planarCompositePotential import planarCompositePotential

MWPotential2014: CompositePotential

class _ExpensivePotentials:
    def __init__(self) -> None: ...
    @override
    def __dir__(self) -> list[str]: ...
    @property
    def McMillan17(self) -> planarCompositePotential | CompositePotential: ...
    @property
    def Cautun20(self) -> planarCompositePotential | CompositePotential: ...
    @property
    def Irrgang13I(self) -> planarCompositePotential | CompositePotential: ...
    @property
    def Irrgang13II(self) -> planarCompositePotential | CompositePotential: ...
    @property
    def Irrgang13III(self) -> planarCompositePotential | CompositePotential: ...
    @property
    def DehnenBinney98I(self) -> planarCompositePotential | CompositePotential: ...
    @property
    def DehnenBinney98II(self) -> planarCompositePotential | CompositePotential: ...
    @property
    def DehnenBinney98III(self) -> planarCompositePotential | CompositePotential: ...
    @property
    def DehnenBinney98IV(self) -> planarCompositePotential | CompositePotential: ...
    def __getattr__(self, name: str) -> CompositePotential: ...

__all__ = ["MWPotential2014"]
