from collections.abc import Generator
from typing import Self, override

from ._typing import Number, Numeric, QuantityLike

class planarForce:
    dim: int
    isDissipative: bool
    _amp: object
    def __init__(
        self,
        amp: QuantityLike = 1.0,
        ro: QuantityLike | None = None,
        vo: QuantityLike | None = None,
    ) -> None: ...
    @override
    def __repr__(self) -> str: ...
    def __mul__(self, b: Number) -> Self: ...
    __rmul__ = __mul__
    def __truediv__(self, b: Number) -> Self: ...
    __div__ = __truediv__
    def __len__(self) -> int: ...
    def __iter__(self) -> Generator[Self]: ...
    def __add__(self, b: planarForce) -> object: ...
    def __radd__(self, b: planarForce) -> object: ...
    def turn_physical_off(self) -> None: ...
    def turn_physical_on(
        self, ro: QuantityLike | None = None, vo: QuantityLike | None = None
    ) -> None: ...
    def Rforce(self, R: Numeric, phi: Numeric = 0.0, t: Numeric = 0.0) -> Numeric: ...
    def phitorque(
        self, R: Numeric, phi: Numeric = 0.0, t: Numeric = 0.0
    ) -> Numeric: ...
