"""
This type stub file was generated by pyright.
"""

class SphericalHarmonicPotentialMixin:
    """Mixin that provides cylindrical force evaluation (_Rforce, _zforce,
    _phitorque) via the chain rule from spherical force components.

    Subclasses must implement ``_compute_spher_forces_at_point(self, R, z, phi, t=0)``
    returning ``(dPhi_dr, dPhi_dtheta, dPhi_dphi)``.
    """

    ...
