from collections.abc import Callable
from typing import overload

from ..potential._typing import Numeric
from optype import numpy as onp

type Pair = tuple[Numeric, Numeric]
type Triple = tuple[Numeric, Numeric, Numeric]
type Transform = Callable[..., object]
type PairOutput = Pair | onp.ArrayND
type TripleOutput = Triple | onp.ArrayND

def scalarDecorator(func: Transform) -> Transform: ...
def degreeDecorator(
    inDegrees: list[int], outDegrees: list[int]
) -> Callable[[Transform], Transform]: ...
@overload
def radec_to_lb(
    ra: float, dec: float, degree: bool = False, epoch: object = 2000.0
) -> Pair: ...
@overload
def radec_to_lb(
    ra: onp.ArrayND, dec: onp.ArrayND, degree: bool = False, epoch: object = 2000.0
) -> onp.ArrayND: ...
def radec_to_lb(
    ra: Numeric, dec: Numeric, degree: bool = False, epoch: object = 2000.0
) -> PairOutput: ...
def lb_to_radec(
    l: Numeric, b: Numeric, degree: bool = False, epoch: object = 2000.0
) -> Pair: ...
@overload
def lbd_to_XYZ(l: float, b: float, d: float, degree: bool = False) -> Triple: ...
@overload
def lbd_to_XYZ(
    l: onp.ArrayND, b: onp.ArrayND, d: onp.ArrayND, degree: bool = False
) -> onp.ArrayND: ...
def lbd_to_XYZ(
    l: Numeric, b: Numeric, d: Numeric, degree: bool = False
) -> TripleOutput: ...
def rectgal_to_sphergal(
    X: Numeric,
    Y: Numeric,
    Z: Numeric,
    vx: Numeric,
    vy: Numeric,
    vz: Numeric,
    degree: bool = False,
) -> tuple[Numeric, Numeric, Numeric, Numeric, Numeric, Numeric]: ...
def sphergal_to_rectgal(
    l: Numeric,
    b: Numeric,
    d: Numeric,
    vr: Numeric,
    pmll: Numeric,
    pmbb: Numeric,
    degree: bool = False,
) -> tuple[Numeric, Numeric, Numeric, Numeric, Numeric, Numeric]: ...
def vrpmllpmbb_to_vxvyvz(
    vr: Numeric,
    pmll: Numeric,
    pmbb: Numeric,
    l: Numeric,
    b: Numeric,
    d: Numeric,
    XYZ: bool = False,
    degree: bool = False,
) -> Triple: ...
def vxvyvz_to_vrpmllpmbb(
    vx: Numeric,
    vy: Numeric,
    vz: Numeric,
    l: Numeric,
    b: Numeric,
    d: Numeric,
    XYZ: bool = False,
    degree: bool = False,
) -> Triple: ...
@overload
def XYZ_to_lbd(X: float, Y: float, Z: float, degree: bool = False) -> Triple: ...
@overload
def XYZ_to_lbd(
    X: onp.ArrayND, Y: onp.ArrayND, Z: onp.ArrayND, degree: bool = False
) -> onp.ArrayND: ...
def XYZ_to_lbd(
    X: Numeric, Y: Numeric, Z: Numeric, degree: bool = False
) -> TripleOutput: ...
def pmrapmdec_to_pmllpmbb(
    pmra: Numeric,
    pmdec: Numeric,
    ra: Numeric,
    dec: Numeric,
    degree: bool = False,
    epoch: object = 2000.0,
) -> Pair: ...
def pmllpmbb_to_pmrapmdec(
    pmll: Numeric,
    pmbb: Numeric,
    l: Numeric,
    b: Numeric,
    degree: bool = False,
    epoch: object = 2000.0,
) -> Pair: ...
def XYZ_to_galcenrect(
    X: Numeric,
    Y: Numeric,
    Z: Numeric,
    Xsun: Numeric = 1.0,
    Zsun: Numeric = 0.0,
    _extra_rot: bool = True,
) -> Triple: ...
def galcenrect_to_XYZ(
    X: Numeric,
    Y: Numeric,
    Z: Numeric,
    Xsun: Numeric = 1.0,
    Zsun: Numeric = 0.0,
    _extra_rot: bool = True,
) -> Triple: ...
def rect_to_cyl(X: Numeric, Y: Numeric, Z: Numeric) -> Triple: ...
def cyl_to_rect(R: Numeric, phi: Numeric, Z: Numeric) -> Triple: ...
def cyl_to_spher(R: Numeric, Z: Numeric, phi: Numeric) -> Triple: ...
def spher_to_cyl(r: Numeric, theta: Numeric, phi: Numeric) -> Triple: ...
def XYZ_to_galcencyl(
    X: Numeric,
    Y: Numeric,
    Z: Numeric,
    Xsun: Numeric = 1.0,
    Zsun: Numeric = 0.0,
    _extra_rot: bool = True,
) -> Triple: ...
def galcencyl_to_XYZ(
    R: Numeric,
    phi: Numeric,
    Z: Numeric,
    Xsun: Numeric = 1.0,
    Zsun: Numeric = 0.0,
    _extra_rot: bool = True,
) -> Triple: ...
def cyl_to_spher_vec(
    vR: Numeric, vT: Numeric, vz: Numeric, R: Numeric, z: Numeric
) -> Triple: ...
def spher_to_cyl_vec(
    vr: Numeric, vT: Numeric, vtheta: Numeric, theta: Numeric
) -> Triple: ...
def rect_to_cyl_vec(
    vx: Numeric,
    vy: Numeric,
    vz: Numeric,
    X: Numeric,
    Y: Numeric,
    Z: Numeric,
    cyl: bool = False,
) -> Triple: ...
def cyl_to_rect_vec(vr: Numeric, vt: Numeric, vz: Numeric, phi: Numeric) -> Triple: ...
def Rz_to_coshucosv(
    R: Numeric, z: Numeric, delta: Numeric = 1.0, oblate: bool = False
) -> Pair: ...
def Rz_to_uv(
    R: Numeric, z: Numeric, delta: Numeric = 1.0, oblate: bool = False
) -> Pair: ...
def uv_to_Rz(
    u: Numeric, v: Numeric, delta: Numeric = 1.0, oblate: bool = False
) -> Pair: ...
def vRvz_to_pupv(
    vR: Numeric,
    vz: Numeric,
    R: Numeric,
    z: Numeric,
    delta: Numeric = 1.0,
    oblate: bool = False,
    uv: bool = False,
) -> Pair: ...
def pupv_to_vRvz(
    pu: Numeric,
    pv: Numeric,
    u: Numeric,
    v: Numeric,
    delta: Numeric = 1.0,
    oblate: bool = False,
) -> Pair: ...
def cov_pmrapmdec_to_pmllpmbb(*args: object, **kwargs: object) -> object: ...
def cov_dvrpmllbb_to_vxyz(*args: object, **kwargs: object) -> object: ...
def cov_vxyz_to_galcencyl(*args: object, **kwargs: object) -> object: ...
def cov_vxyz_to_galcenrect(*args: object, **kwargs: object) -> object: ...
def cov_galcenrect_to_galcencyl(*args: object, **kwargs: object) -> object: ...
def vxvyvz_to_galcenrect(*args: object, **kwargs: object) -> object: ...
def vxvyvz_to_galcencyl(*args: object, **kwargs: object) -> object: ...
def galcenrect_to_vxvyvz(*args: object, **kwargs: object) -> object: ...
def galcencyl_to_vxvyvz(*args: object, **kwargs: object) -> object: ...
def cyl_to_rect_jac(*args: object, **kwargs: object) -> object: ...
def galcenrect_to_XYZ_jac(*args: object, **kwargs: object) -> object: ...
def lbd_to_XYZ_jac(*args: object, **kwargs: object) -> object: ...
def XYZ_to_lbd_jac(*args: object, **kwargs: object) -> object: ...
def galcenrect_to_galcencyl_jac(*args: object, **kwargs: object) -> object: ...
def galsky_to_sky_jac(*args: object, **kwargs: object) -> object: ...
def sky_to_customsky_jac(*args: object, **kwargs: object) -> object: ...
def dl_to_rphi_2d(*args: object, **kwargs: object) -> object: ...
def rphi_to_dl_2d(*args: object, **kwargs: object) -> object: ...
def Rz_to_lambdanu(*args: object, **kwargs: object) -> object: ...
def Rz_to_lambdanu_jac(*args: object, **kwargs: object) -> object: ...
def Rz_to_lambdanu_hess(*args: object, **kwargs: object) -> object: ...
def lambdanu_to_Rz(*args: object, **kwargs: object) -> object: ...
def radec_to_custom(*args: object, **kwargs: object) -> object: ...
def pmrapmdec_to_custom(*args: object, **kwargs: object) -> object: ...
def custom_to_radec(*args: object, **kwargs: object) -> object: ...
def custom_to_pmrapmdec(*args: object, **kwargs: object) -> object: ...
def align_to_orbit(*args: object, **kwargs: object) -> object: ...
def get_epoch_angles(epoch: object = 2000.0) -> Triple: ...
