from optype import numpy as onp

def end_print(filename: str, **kwargs: object) -> None: ...
def hist(
    x: onp.ArrayND,
    xlabel: str | None = None,
    ylabel: str | None = None,
    overplot: bool = False,
    **kwargs: object,
) -> tuple[onp.ArrayND | list[onp.ArrayND], onp.ArrayND, object]: ...
def plot(*args: object, **kwargs: object) -> object: ...
def plot3d(*args: object, **kwargs: object) -> list[object]: ...
def dens2d(X: onp.ArrayND, **kwargs: object) -> object: ...
def start_print(filename: str | None = None, **kwargs: object) -> None: ...
def text(*args: object, **kwargs: object) -> None: ...
def scatterplot(
    x: onp.ArrayND, y: onp.ArrayND, *args: object, **kwargs: object
) -> object: ...

class GalPolarAxes:
    """Matplotlib polar axes with galpy's clockwise theta convention."""

    name: str

    class GalPolarTransform:
        def transform(self, tr: object) -> onp.Array1D: ...
        def inverted(self) -> GalPolarAxes.InvertedGalPolarTransform: ...

    class InvertedGalPolarTransform:
        def transform(self, xy: onp.ArrayND) -> onp.ArrayND: ...
        def inverted(self) -> GalPolarAxes.GalPolarTransform: ...
