from ..potential._typing import Numeric
from ..potential.Potential import Potential
from .df import df

class evolveddiskdf(df):
    def __init__(
        self, initdf: object, pot: Potential | list[Potential], to: Numeric = 0.0
    ) -> None: ...
    def __call__(self, *args: object, **kwargs: object) -> object: ...
    def vmomentsurfacemass(self, *args: object, **kwargs: object) -> object: ...
    def vertexdev(self, *args: object, **kwargs: object) -> object: ...
    def meanvR(self, *args: object, **kwargs: object) -> object: ...
    def meanvT(self, *args: object, **kwargs: object) -> object: ...
    def sigmaR2(self, *args: object, **kwargs: object) -> object: ...
    def sigmaT2(self, *args: object, **kwargs: object) -> object: ...
    def sigmaRT(self, *args: object, **kwargs: object) -> object: ...
    def oortA(self, *args: object, **kwargs: object) -> object: ...
    def oortB(self, *args: object, **kwargs: object) -> object: ...
    def oortC(self, *args: object, **kwargs: object) -> object: ...
    def oortK(self, *args: object, **kwargs: object) -> object: ...

class evolveddiskdfGrid:
    def __init__(self) -> None: ...
    def plot(self, tt: Numeric = 0.0) -> None: ...

class evolveddiskdfHierarchicalGrid:
    def __init__(
        self,
        edf: evolveddiskdf,
        R: Numeric,
        phi: Numeric,
        nsigma: int,
        t: Numeric,
        sigmaR1: Numeric,
        sigmaT1: Numeric,
        meanvR: Numeric,
        meanvT: Numeric,
        gridpoints: object,
        nlevels: int,
        deriv: object,
        upperdxdy: object = None,
        print_progress: bool = False,
        nlevelsTotal: int | None = None,
    ) -> None: ...
    def __call__(self, n: int, m: int) -> object: ...
    def plot(self, *args: object, **kwargs: object) -> None: ...
    def max(self, tt: Numeric = 0.0) -> float: ...
