from optype import numpy as onp

from ..potential._typing import Numeric, QuantityLike
from ..potential.Potential import Potential
from .df import df

type SphericalPotentialInput = Potential | list[Potential]

class sphericaldf(df):
    def __init__(
        self,
        pot: SphericalPotentialInput | None = None,
        denspot: SphericalPotentialInput | None = None,
        rmax: Numeric | QuantityLike | None = None,
        scale: Numeric | QuantityLike | None = None,
        ro: Numeric | None = None,
        vo: Numeric | None = None,
    ) -> None: ...
    def __call__(self, *args: object, **kwargs: object) -> object: ...
    def dMdE(self, E: Numeric) -> object: ...
    def vmomentdensity(
        self, r: Numeric, n: int, m: int, **kwargs: object
    ) -> object: ...
    def sigmar(self, r: Numeric) -> object: ...
    def sigmat(self, r: Numeric) -> object: ...
    def beta(self, r: Numeric) -> Numeric: ...
    def sample(self, *args: object, **kwargs: object) -> object: ...

class isotropicsphericaldf(sphericaldf):
    def fE(self, E: onp.ArrayND) -> onp.ArrayND: ...

class anisotropicsphericaldf(sphericaldf):
    def fE(self, E: onp.ArrayND) -> onp.ArrayND: ...
    def fQ(self, Q: onp.ArrayND) -> onp.ArrayND: ...
