from typing import Self

from optype import numpy as onp

from ..potential._typing import Numeric, QuantityLike

class StreamTrack:
    """Smooth phase-space track for one stream arm."""

    def __init__(
        self,
        tp_grid: onp.Array1D,
        track_xyz: onp.Array2D,
        track_vxvyvz: onp.Array2D,
        cov_xyz: onp.Array3D | None = None,
        custom_sky_transform: onp.Array2D | None = None,
        parameter_kind: str | None = "time",
        ro: Numeric | None = None,
        vo: Numeric | None = None,
        zo: Numeric | None = None,
        solarmotion: str | onp.Array1D | QuantityLike | None = None,
    ) -> None: ...
    @classmethod
    def from_particles(cls, *args: object, **kwargs: object) -> Self: ...
    def tp_grid(self) -> onp.Array1D: ...
    def __call__(self, tp: Numeric | onp.ArrayND) -> onp.ArrayND: ...
    def x(self, tp: Numeric | onp.ArrayND, **kwargs: object) -> object: ...
    def y(self, tp: Numeric | onp.ArrayND, **kwargs: object) -> object: ...
    def z(self, tp: Numeric | onp.ArrayND, **kwargs: object) -> object: ...
    def vx(self, tp: Numeric | onp.ArrayND, **kwargs: object) -> object: ...
    def vy(self, tp: Numeric | onp.ArrayND, **kwargs: object) -> object: ...
    def vz(self, tp: Numeric | onp.ArrayND, **kwargs: object) -> object: ...
    def R(self, tp: Numeric | onp.ArrayND, **kwargs: object) -> object: ...
    def vR(self, tp: Numeric | onp.ArrayND, **kwargs: object) -> object: ...
    def vT(self, tp: Numeric | onp.ArrayND, **kwargs: object) -> object: ...
    def phi(self, tp: Numeric | onp.ArrayND, **kwargs: object) -> object: ...
    def cov(self, tp: Numeric | onp.ArrayND, **kwargs: object) -> object: ...
    def turn_physical_on(
        self, ro: Numeric | None = None, vo: Numeric | None = None
    ) -> None: ...
    def turn_physical_off(self) -> None: ...
    def plot(self, *args: object, **kwargs: object) -> list[object]: ...
    def __getattr__(self, name: str) -> object: ...

class StreamTrackPair:
    def __init__(self, leading: StreamTrack, trailing: StreamTrack) -> None: ...
    def particles(self) -> onp.ArrayND: ...
    def turn_physical_on(
        self, ro: Numeric | None = None, vo: Numeric | None = None
    ) -> None: ...
    def turn_physical_off(self) -> None: ...
    def plot(self, *args: object, **kwargs: object) -> list[object]: ...
    def __getattr__(self, name: str) -> object: ...
