from collections.abc import Callable

from ..potential._typing import Numeric
from .streamdf import streamdf

class streamgapdf(streamdf):
    def __init__(self, *args: object, **kwargs: object) -> None: ...
    def pOparapar(self, Opar: Numeric, apar: Numeric) -> object: ...
    def minOpar(self, dangle: Numeric, **kwargs: object) -> object: ...
    def meanOmega(self, dangle: Numeric, **kwargs: object) -> object: ...

def impact_check_range(func: Callable[..., object]) -> Callable[..., object]: ...
def impulse_deltav_plummer(*args: object, **kwargs: object) -> object: ...
def impulse_deltav_plummer_curvedstream(*args: object, **kwargs: object) -> object: ...
def HernquistX(s: Numeric) -> Numeric: ...
def impulse_deltav_hernquist(*args: object, **kwargs: object) -> object: ...
def impulse_deltav_hernquist_curvedstream(
    *args: object, **kwargs: object
) -> object: ...
def impulse_deltav_general(*args: object, **kwargs: object) -> object: ...
def impulse_deltav_general_curvedstream(*args: object, **kwargs: object) -> object: ...
def impulse_deltav_general_orbitintegration(
    *args: object, **kwargs: object
) -> object: ...
def impulse_deltav_general_fullplummerintegration(
    *args: object, **kwargs: object
) -> object: ...
def impulse_deltav_plummerstream(*args: object, **kwargs: object) -> object: ...
def impulse_deltav_plummerstream_curvedstream(
    *args: object, **kwargs: object
) -> object: ...
