from collections.abc import Callable
from typing import Literal, Self

from optype import numpy as onp

from ..potential._typing import Numeric, QuantityLike
from ..potential.Potential import Potential

type OrbitInput = onp.ArrayND | QuantityLike | list[object] | None
type TimeInput = Numeric | QuantityLike | onp.ArrayND | list[Numeric]

def name_completer(ipython: object, event: object) -> list[str] | None: ...
def shapeDecorator(func: Callable[..., object]) -> Callable[..., object]: ...

class Orbit:
    """Single or multiple galpy orbits with shape-preserving accessors."""

    def __init__(
        self,
        vxvv: OrbitInput = None,
        ro: Numeric | QuantityLike | None = None,
        vo: Numeric | QuantityLike | None = None,
        zo: Numeric | QuantityLike | None = None,
        solarmotion: str | onp.Array1D | QuantityLike | None = None,
        radec: bool = False,
        uvw: bool = False,
        lb: bool = False,
    ) -> None: ...
    @classmethod
    def from_name(cls, name: str | list[str], **kwargs: object) -> Self: ...
    @classmethod
    def from_fit(cls, *args: object, **kwargs: object) -> Self: ...
    def __len__(self) -> int: ...
    def __getitem__(self, key: object) -> Self: ...
    def __call__(self, *args: object, **kwargs: object) -> Self: ...
    def dim(self) -> Literal[1, 2, 3] | None: ...
    def phasedim(self) -> int: ...
    def reshape(self, newshape: int | tuple[int, ...]) -> None: ...
    def turn_physical_off(self) -> None: ...
    def turn_physical_on(
        self,
        ro: Numeric | QuantityLike | bool | None = None,
        vo: Numeric | QuantityLike | bool | None = None,
    ) -> None: ...
    @staticmethod
    def check_integrator(method: str, no_symplec: bool = False) -> None: ...
    def integrate(
        self,
        t: TimeInput | Potential,
        pot: object = None,
        method: str = "symplec4_c",
        progressbar: bool = True,
        dt: Numeric | QuantityLike | None = None,
        numcores: int = 1,
        force_map: bool = False,
        rtol: float | None = None,
        atol: float | None = None,
    ) -> None: ...
    def integrate_dxdv(self, *args: object, **kwargs: object) -> None: ...
    def integrate_SOS(self, *args: object, **kwargs: object) -> None: ...
    def getOrbit(self) -> object: ...
    def getOrbit_dxdv(self) -> object: ...
    def flip(self, inplace: bool = False) -> Self | None: ...
    def time(self, *args: object, **kwargs: object) -> object: ...
    def name(self, *args: object, **kwargs: object) -> object: ...
    def R(self, *args: object, **kwargs: object) -> object: ...
    def vR(self, *args: object, **kwargs: object) -> object: ...
    def vT(self, *args: object, **kwargs: object) -> object: ...
    def z(self, *args: object, **kwargs: object) -> object: ...
    def vz(self, *args: object, **kwargs: object) -> object: ...
    def phi(self, *args: object, **kwargs: object) -> object: ...
    def x(self, *args: object, **kwargs: object) -> object: ...
    def y(self, *args: object, **kwargs: object) -> object: ...
    def vx(self, *args: object, **kwargs: object) -> object: ...
    def vy(self, *args: object, **kwargs: object) -> object: ...
    def r(self, *args: object, **kwargs: object) -> object: ...
    def vr(self, *args: object, **kwargs: object) -> object: ...
    def vphi(self, *args: object, **kwargs: object) -> object: ...
    def ra(self, *args: object, **kwargs: object) -> object: ...
    def dec(self, *args: object, **kwargs: object) -> object: ...
    def ll(self, *args: object, **kwargs: object) -> object: ...
    def bb(self, *args: object, **kwargs: object) -> object: ...
    def dist(self, *args: object, **kwargs: object) -> object: ...
    def pmra(self, *args: object, **kwargs: object) -> object: ...
    def pmdec(self, *args: object, **kwargs: object) -> object: ...
    def pmll(self, *args: object, **kwargs: object) -> object: ...
    def pmbb(self, *args: object, **kwargs: object) -> object: ...
    def vlos(self, *args: object, **kwargs: object) -> object: ...
    def U(self, *args: object, **kwargs: object) -> object: ...
    def V(self, *args: object, **kwargs: object) -> object: ...
    def W(self, *args: object, **kwargs: object) -> object: ...
    def helioX(self, *args: object, **kwargs: object) -> object: ...
    def helioY(self, *args: object, **kwargs: object) -> object: ...
    def helioZ(self, *args: object, **kwargs: object) -> object: ...
    def e(self, *args: object, **kwargs: object) -> object: ...
    def rap(self, *args: object, **kwargs: object) -> object: ...
    def rperi(self, *args: object, **kwargs: object) -> object: ...
    def zmax(self, *args: object, **kwargs: object) -> object: ...
    def L(self, *args: object, **kwargs: object) -> object: ...
    def Lz(self, *args: object, **kwargs: object) -> object: ...
    def Jacobi(self, *args: object, **kwargs: object) -> object: ...
    def E(self, *args: object, **kwargs: object) -> object: ...
    def get_physical(self) -> dict[str, object]: ...
    def plot(self, *args: object, **kwargs: object) -> object: ...
    def plot3d(self, *args: object, **kwargs: object) -> object: ...
    def animate(self, **kwargs: object) -> object: ...
    def animate3d(self, **kwargs: object) -> object: ...
    def __getattr__(self, name: str) -> object: ...
