from typing import override

from optype import numpy as onp

class Snapshot:
    def __init__(self, *args: object, **kwargs: object) -> None: ...
    def integrate(
        self,
        t: onp.Array1D,
        pot: object = None,
        method: str = "test-particle",
        **kwargs: object,
    ) -> list[Snapshot] | None: ...
    def plot(self, *args: object, **kwargs: object) -> object: ...
    def plot3d(self, *args: object, **kwargs: object) -> object: ...
    @override
    def __getstate__(self) -> tuple[object, object]: ...
    def __setstate__(self, state: object) -> None: ...
