from .util.config import configfilename as configfilename
from .util.config import write_config as write_config

__version__: str

def latest_pypi_version(name: str) -> str: ...
def check_pypi_version(name: str) -> bool: ...
def print_version_warning() -> None: ...
