from collections.abc import Generator
from typing import Self, override

class baseCompositePotential:
    _potlist: list[object]
    def __len__(self) -> int: ...
    def __getitem__(self, key: int | slice) -> object | Self: ...
    def __setitem__(self, key: int | slice, value: object) -> None: ...
    def __iter__(self) -> Generator[Self, None, None]: ...
    @override
    def __eq__(self, other: object) -> bool: ...
    def __mul__(self, b: int | float) -> Self: ...
    __rmul__ = __mul__
    def __truediv__(self, b: int | float) -> Self: ...
    __div__ = __truediv__
    def turn_physical_off(self) -> None: ...
    def turn_physical_on(
        self, ro: object | None = None, vo: object | None = None
    ) -> None: ...
    @override
    def __repr__(self) -> str: ...
