from .CompositePotential import CompositePotential
from .planarCompositePotential import planarCompositePotential

ro = ...
Rm_ISM = ...
zd_ISM = ...
zd_thin = ...
zd_thick = ...
Rd_ISM_over_Rd = ...
Rd_thin_over_Rd = ...
Rd_thick_over_Rd = ...
SigmaR0_ISM_over_SigmaR0 = ...
SigmaR0_thin_over_SigmaR0 = ...
SigmaR0_thick_over_SigmaR0 = ...
alpha_bulge = ...
q_bulge = ...
r0_bulge = ...
rc_bulge = ...
q_halo = ...

def define_dehnenbinney98_models(
    model: int = 1,
) -> planarCompositePotential | CompositePotential: ...
