from collections.abc import Generator
from typing import Self, override

from ._typing import Number, QuantityLike, Numeric

class Force:
    _amp: object
    _ro: float
    _vo: float
    _roSet: bool
    _voSet: bool
    isDissipative: bool

    def __init__(
        self,
        amp: QuantityLike = 1.0,
        ro: QuantityLike | None = None,
        vo: QuantityLike | None = None,
        amp_units: str | None = None,
    ) -> None: ...
    @override
    def __repr__(self) -> str: ...
    def __mul__(self, b: Number) -> Self: ...
    __rmul__: Self
    def __truediv__(self, b: Number) -> Self: ...
    __div__: Self
    def __len__(self) -> int: ...
    def __iter__(self) -> Generator[Self, None, None]: ...
    def __add__(self, b: Force) -> object: ...
    def __radd__(self, b: Force) -> object: ...
    def turn_physical_off(self) -> None: ...
    def turn_physical_on(
        self, ro: QuantityLike | None = None, vo: QuantityLike | None = None
    ) -> None: ...
    def rforce(self, R: Numeric, z: Numeric, **kwargs: object) -> Numeric: ...
    def toPlanar(self) -> object: ...
