from typing import override

from ..potential._typing import Numeric

class surfaceSigmaProfile:
    def __init__(self) -> None: ...
    def formatStringParams(self) -> list[str]: ...
    def outputParams(self) -> tuple[object, ...]: ...
    def surfacemass(self, R: Numeric, log: bool = False) -> Numeric: ...
    def sigma2(self, R: Numeric, log: bool = False) -> Numeric: ...

class expSurfaceSigmaProfile(surfaceSigmaProfile):
    def __init__(
        self, params: tuple[float, float, float] = (1 / 3, 1.0, 0.2)
    ) -> None: ...
    @override
    def surfacemass(self, R: Numeric, log: bool = False) -> Numeric: ...
    @override
    def sigma2(self, R: Numeric, log: bool = False) -> Numeric: ...
