from collections.abc import Callable

from ..potential._typing import Number, Numeric, QuantityLike

type ConversionInput = Numeric | QuantityLike
type ConversionOutput = Numeric | QuantityLike
type DecoratedCallable = Callable[..., object]
type ConversionDecorator = Callable[[DecoratedCallable], DecoratedCallable]

_G: float
_GHBARINKM3S3KPC2: float
_kmsInPcMyr: float
_PCIN10p18CM: float
_CIN10p5KMS: float
_MSOLAR10p30KG: float
_EVIN10m19J: float
_JIN10p10KM2S2Msun: float
_MyrIn1013Sec: float
_TWOPI: float

def dens_in_criticaldens(vo: Number, ro: Number, H: Number = 70.0) -> float: ...
def dens_in_meanmatterdens(
    vo: Number, ro: Number, H: Number = 70.0, Om: Number = 0.3
) -> float: ...
def dens_in_gevcc(vo: Number, ro: Number) -> float: ...
def dens_in_msolpc3(vo: Number, ro: Number) -> float: ...
def force_in_2piGmsolpc2(vo: Number, ro: Number) -> float: ...
def force_in_pcMyr2(vo: Number, ro: Number) -> float: ...
def force_in_kmsMyr(vo: Number, ro: Number) -> float: ...
def force_in_10m13kms2(vo: Number, ro: Number) -> float: ...
def freq_in_Gyr(vo: Number, ro: Number) -> float: ...
def freq_in_kmskpc(vo: Number, ro: Number) -> float: ...
def surfdens_in_msolpc2(vo: Number, ro: Number) -> float: ...
def mass_in_msol(vo: Number, ro: Number) -> float: ...
def mass_in_1010msol(vo: Number, ro: Number) -> float: ...
def time_in_Gyr(vo: Number, ro: Number) -> float: ...
def velocity_in_kpcGyr(vo: Number, ro: Number) -> float: ...
def get_physical(obj: object, include_set: bool = False) -> dict[str, object]: ...
def extract_physical_kwargs(kwargs: dict[str, object]) -> dict[str, object]: ...
def physical_compatible(obj: object, other_obj: object) -> bool: ...
def check_parser_input_type(func: DecoratedCallable) -> DecoratedCallable: ...
def parse_length(
    x: ConversionInput,
    ro: ConversionInput | None = None,
    vo: ConversionInput | None = None,
) -> ConversionOutput: ...
def parse_length_kpc(x: ConversionInput) -> ConversionOutput: ...
def parse_velocity(
    x: ConversionInput,
    ro: ConversionInput | None = None,
    vo: ConversionInput | None = None,
) -> ConversionOutput: ...
def parse_velocity_kms(x: ConversionInput) -> ConversionOutput: ...
def parse_angle(x: ConversionInput) -> ConversionOutput: ...
def parse_time(
    x: ConversionInput,
    ro: ConversionInput | None = None,
    vo: ConversionInput | None = None,
) -> ConversionOutput: ...
def parse_mass(
    x: ConversionInput,
    ro: ConversionInput | None = None,
    vo: ConversionInput | None = None,
) -> ConversionOutput: ...
def parse_energy(
    x: ConversionInput,
    ro: ConversionInput | None = None,
    vo: ConversionInput | None = None,
) -> ConversionOutput: ...
def parse_angmom(
    x: ConversionInput,
    ro: ConversionInput | None = None,
    vo: ConversionInput | None = None,
) -> ConversionOutput: ...
def parse_frequency(
    x: ConversionInput,
    ro: ConversionInput | None = None,
    vo: ConversionInput | None = None,
) -> ConversionOutput: ...
def parse_force(
    x: ConversionInput,
    ro: ConversionInput | None = None,
    vo: ConversionInput | None = None,
) -> ConversionOutput: ...
def parse_dens(
    x: ConversionInput,
    ro: ConversionInput | None = None,
    vo: ConversionInput | None = None,
) -> ConversionOutput: ...
def parse_surfdens(
    x: ConversionInput,
    ro: ConversionInput | None = None,
    vo: ConversionInput | None = None,
) -> ConversionOutput: ...
def parse_numdens(
    x: ConversionInput,
    ro: ConversionInput | None = None,
    vo: ConversionInput | None = None,
) -> ConversionOutput: ...
def physical_output(
    obj: object, kwargs: dict[str, object], quantity: str
) -> tuple[bool, float, float]: ...
def physical_conversion(quantity: str, pop: bool = False) -> ConversionDecorator: ...
def physical_conversion_tuple(
    quantities: list[str] | tuple[str, ...], pop: bool = False
) -> ConversionDecorator: ...
def potential_physical_input(method: DecoratedCallable) -> DecoratedCallable: ...
def physical_conversion_actionAngle(
    quantity: str, pop: bool = False
) -> ConversionDecorator: ...
def actionAngle_physical_input(method: DecoratedCallable) -> DecoratedCallable: ...
def physical_conversion_actionAngleInverse(
    quantity: str, pop: bool = False
) -> ConversionDecorator: ...
def actionAngleInverse_physical_input(
    method: DecoratedCallable,
) -> DecoratedCallable: ...
